import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";

const inter = localFont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});
const spaceGrotesk = localFont({
  src: "./fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700 ",
});

export const metadata: Metadata = {
  title: "Hello Hemanth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${spaceGrotesk.variable}  antialiased`}
      >
        <h1 className="text-3xl font-black text-primary-500">Main ROOT</h1>
        {children}
      </body>
    </html>
  );
}
